version: '3'

services:
  ############################
  # Setup the webpack container
  ############################
  webpack:
    container_name: webpack
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=development

